#include <stdio.h>
#include <stdlib.h>

/* Generated by DeepSeek. Didn't know how hash tables work at the time */

// Structure for the hash table node
typedef struct Node {
    int key;
    int value;
    struct Node* next;
} Node;

// Structure for the hash table
typedef struct HashTable {
    int size;
    Node** table;
} HashTable;

// Function to create a new node
Node* createNode(int key, int value) {
    Node* newNode = (Node*)malloc(sizeof(Node));
    newNode->key = key;
    newNode->value = value;
    newNode->next = NULL;
    return newNode;
}

// Function to create a hash table
HashTable* createHashTable(int size) {
    HashTable* ht = (HashTable*)malloc(sizeof(HashTable));
    ht->size = size;
    ht->table = (Node**)malloc(sizeof(Node*) * size);
    for (int i = 0; i < size; i++) {
        ht->table[i] = NULL;
    }
    return ht;
}

// Simple hash function
int hash(int key, int size) {
    return abs(key) % size;
}

// Function to insert a key-value pair into the hash table
void insert(HashTable* ht, int key, int value) {
    int index = hash(key, ht->size);
    Node* newNode = createNode(key, value);
    newNode->next = ht->table[index];
    ht->table[index] = newNode;
}

// Function to lookup a key in the hash table
int lookup(HashTable* ht, int key) {
    int index = hash(key, ht->size);
    Node* current = ht->table[index];
    while (current != NULL) {
        if (current->key == key) {
            return current->value;
        }
        current = current->next;
    }
    return -1; // Not found
}

// Function to free the hash table
void freeHashTable(HashTable* ht) {
    for (int i = 0; i < ht->size; i++) {
        Node* current = ht->table[i];
        while (current != NULL) {
            Node* temp = current;
            current = current->next;
            free(temp);
        }
    }
    free(ht->table);
    free(ht);
}

// Two Sum function
int* twoSum(int* nums, int numsSize, int target, int* returnSize) {
    HashTable* ht = createHashTable(numsSize);
    int* result = (int*)malloc(2 * sizeof(int));
    *returnSize = 2;

    for (int i = 0; i < numsSize; i++) {
        int complement = target - nums[i];
        int complementIndex = lookup(ht, complement);
        if (complementIndex != -1) {
            result[0] = complementIndex;
            result[1] = i;
            freeHashTable(ht);
            return result;
        }
        insert(ht, nums[i], i);
    }

    freeHashTable(ht);
    return NULL; // In case no solution found (though problem states one exists)
}

// Example usage
int main() {
    int nums[] = {2, 7, 11, 15};
    int target = 9;
    int returnSize;
    int* result = twoSum(nums, 4, target, &returnSize);

    if (result != NULL) {
        printf("[%d, %d]\n", result[0], result[1]);
        free(result);
    } else {
        printf("No solution found.\n");
    }

    return 0;
}

/* Python:
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        num_map = {}
        for i, num in enumerate(nums):
            complement = target - num
            if complement in num_map:
                return [num_map[complement], i]
            num_map[num] = i
        return []
*/
